from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('index/',views.index),

    path('csv2Model/',views.csv2Model),

    path('DadaepoBeach/',views.DadaepoBeach),
    path('DadaepoHarbor/',views.DadaepoHarbor),
    path('Natgae/',views.Natgae),
    path('Sinjangnim/',views.Sinjangnim),
    path('Jangnim/',views.Jangnim),
    path('Dongmae/',views.Dongmae),
    path('Sinpyeong/',views.Sinpyeong),
    path('Hadan/',views.Hadan),
    path('Dangni/',views.Dangni),
    path('Saha/',views.Saha),
    path('Goejeong/',views.Goejeong),
    path('Daeti/',views.Daeti),
    path('Seodaesin/',views.Seodaesin),
    path('Dongdaesin/',views.Dongdaesin),
    path('Toseong/',views.Toseong),
    path('Jagalchi/',views.Jagalchi),
    path('Nampo/',views.Nampo),
    path('Jungang/',views.Jungang),
    path('BusanStation/',views.BusanStation),
    path('Choryang/',views.Choryang),
    path('Busanjin/',views.Busanjin),
    path('Jwacheon/',views.Jwacheon),
    path('Beomil/',views.Beomil),
    path('Beomnaegol/',views.Beomnaegol),
    path('Seomyeon/',views.Seomyeon),
    path('Bujeon/',views.Bujeon),
    path('Yangjeong/',views.Yangjeong),
    path('CityHall/',views.CityHall),
    path('Yeonsan/',views.Yeonsan),
    path('BusanNatlUnivEdu/',views.BusanNatlUnivEdu),
    path('Dongnae/',views.Dongnae),
    path('Myeongnyun/',views.Myeongnyun),
    path('Oncheonjang/',views.Oncheonjang),
    path('PusanNatlUniv/',views.PusanNatlUniv),
    path('Jangjeon/',views.Jangjeon),
    path('Guseo/',views.Guseo),
    path('Dusil/',views.Dusil),
    path('Namsan/',views.Namsan),
    path('Beomeosa/',views.Beomeosa),    
    path('Nopo/',views.Nopo),
    
]
