# Generated by Django 4.0.5 on 2022-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationKor', models.CharField(max_length=100)),
                ('stationEng', models.CharField(max_length=100)),
                ('stationNum', models.IntegerField(default=0)),
                ('stationTip', models.CharField(max_length=200)),
            ],
        ),
    ]
