# Generated by Django 4.0.5 on 2022-06-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendByStation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='stationTel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
