# Generated by Django 4.0.5 on 2022-06-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendByStation', '0002_stationinfo_stationtel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='stationBikeStorage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='stationItemStorage',
            field=models.BooleanField(default=False),
        ),
    ]
